services:
  web:
    build:
      context: .
    volumes:
      - ./:/workspace
    command: /bin/bash
      # command: python sample.py && /bin/bash
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

